import { boxDefaultProps } from 'components/box';

/**
 * captionDefaultProps - define defaultProps used by Caption component or extensions of CaptionContainer component.
 * 
 * propDefaults can be used to overide the style fallbacks,
 * style fallbacks are defined in the component's stylesheet.
 * See styled-component in `./caption.css.js`
 * 
 * Since components can be extensions of other components with styled-components,
 * this means some components will share common props, this helps not to repeatedly rewrite defaultProps.
 * To import captionDefaultProps do: `import { captionDefaultProps } from 'components/caption';
 */
const captionDefaultProps = {
    ...boxDefaultProps,
    as: 'figcaption',
    backgroundColor: 'transparent',
    captionType: undefined,
    context: undefined,
    contextAlign: undefined,
    contextAs: 'h2',
    contextBackgroundColor: undefined,
    contextBorder: undefined,
    contextBorderBottom: undefined,
    contextBorderColor: undefined,
    contextBorderLeft: undefined,
    contextBorderRadius: undefined,
    contextBorderRight: undefined,
    contextBorderTop: undefined,
    contextBoxShadow: undefined,
    contextBoxTransform: undefined,
    contextColor: 'gray0',
    contextDecoration: undefined,
    contextFont: undefined,
    contextKerning: undefined,
    contextMargin: undefined,
    contextMarginBottom: undefined,
    contextMarginLeft: undefined,
    contextMarginRight: undefined,
    contextMarginTop: undefined,
    contextMaxWidth: undefined,
    contextMinWidth: undefined,
    contextOpacity: undefined,
    contextOrder: undefined,
    contextPadding: undefined,
    contextPaddingBottom: undefined,
    contextPaddingLeft: undefined,
    contextPaddingRight: undefined,
    contextPaddingTop: undefined,
    contextShadow: undefined,
    contextSize: undefined,
    contextTracking: undefined,
    contextTransform: undefined,
    contextTransition: undefined,
    contextType: 'subheading',
    contextWeight: undefined,
    contextWidth: undefined,
    contextZIndex: undefined,
    heading: undefined,
    headingAlign: undefined,
    headingAs: 'h1',
    headingBackgroundColor: undefined,
    headingBorder: undefined,
    headingBorderBottom: undefined,
    headingBorderColor: undefined,
    headingBorderLeft: undefined,
    headingBorderRadius: undefined,
    headingBorderRight: undefined,
    headingBorderTop: undefined,
    headingBoxShadow: undefined,
    headingBoxTransform: undefined,
    headingColor: 'black',
    headingDecoration: undefined,
    headingFont: undefined,
    headingKerning: undefined,
    headingMargin: undefined,
    headingMarginBottom: undefined,
    headingMarginLeft: undefined,
    headingMarginRight: undefined,
    headingMarginTop: undefined,
    headingMaxWidth: undefined,
    headingMinWidth: undefined,
    headingOpacity: undefined,
    headingOrder: undefined,
    headingPadding: undefined,
    headingPaddingBottom: undefined,
    headingPaddingLeft: undefined,
    headingPaddingRight: undefined,
    headingPaddingTop: undefined,
    headingShadow: undefined,
    headingSize: undefined,
    headingTracking: undefined,
    headingTransform: undefined,
    headingTransition: undefined,
    headingType: 'heading',
    headingWeight: undefined,
    headingWidth: undefined,
    headingZIndex: undefined,
};

export default captionDefaultProps;
