import PropTypes from 'prop-types';
import { boxPropTypes } from 'components/box';

/**
 * captionPropTypes - define propTypes used by Caption component or extensions of CaptionContainer component.
 * 
 * Since components can be extensions of other components with styled-components,
 * this means some components will share common props, this helps not to repeatedly rewrite propTypes.
 * to import captionPropTypes do: `import { captionPropTypes } from 'components/caption';
 */
const captionPropTypes = {
    ...boxPropTypes,
    captionType: PropTypes.string,
    context: PropTypes.string,
    contextAlign: PropTypes.string,
    contextAs: PropTypes.string,
    contextBackgroundColor: PropTypes.string,
    contextBorder: PropTypes.string,
    contextBorderBottom: PropTypes.string,
    contextBorderColor: PropTypes.string,
    contextBorderLeft: PropTypes.string,
    contextBorderRadius: PropTypes.string,
    contextBorderRight: PropTypes.string,
    contextBorderTop: PropTypes.string,
    contextBoxShadow: PropTypes.string,
    contextBoxTransform: PropTypes.string,
    contextColor: PropTypes.string,
    contextDecoration: PropTypes.string,
    contextFont: PropTypes.string,
    contextKerning: PropTypes.string,
    contextMargin: PropTypes.string,
    contextMarginBottom: PropTypes.string,
    contextMarginLeft: PropTypes.string,
    contextMarginRight: PropTypes.string,
    contextMarginTop: PropTypes.string,
    contextMaxWidth: PropTypes.string,
    contextMinWidth: PropTypes.string,
    contextOpacity: PropTypes.number,
    contextOrder: PropTypes.number,
    contextPadding: PropTypes.string,
    contextPaddingBottom: PropTypes.string,
    contextPaddingLeft: PropTypes.string,
    contextPaddingRight: PropTypes.string,
    contextPaddingTop: PropTypes.string,
    contextShadow: PropTypes.string,
    contextSize: PropTypes.string,
    contextTracking: PropTypes.string,
    contextTransform: PropTypes.string,
    contextTransition: PropTypes.string,
    contextType: PropTypes.string,
    contextWeight: PropTypes.string,
    contextWidth: PropTypes.string,
    contextZIndex: PropTypes.number,
    heading: PropTypes.string,
    headingAlign: PropTypes.string,
    headingAs: PropTypes.string,
    headingBackgroundColor: PropTypes.string,
    headingBorder: PropTypes.string,
    headingBorderBottom: PropTypes.string,
    headingBorderColor: PropTypes.string,
    headingBorderLeft: PropTypes.string,
    headingBorderRadius: PropTypes.string,
    headingBorderRight: PropTypes.string,
    headingBorderTop: PropTypes.string,
    headingBoxShadow: PropTypes.string,
    headingBoxTransform: PropTypes.string,
    headingColor: PropTypes.string,
    headingDecoration: PropTypes.string,
    headingFont: PropTypes.string,
    headingKerning: PropTypes.string,
    headingMargin: PropTypes.string,
    headingMarginBottom: PropTypes.string,
    headingMarginLeft: PropTypes.string,
    headingMarginRight: PropTypes.string,
    headingMarginTop: PropTypes.string,
    headingMaxWidth: PropTypes.string,
    headingMinWidth: PropTypes.string,
    headingOpacity: PropTypes.number,
    headingOrder: PropTypes.number,
    headingPadding: PropTypes.string,
    headingPaddingBottom: PropTypes.string,
    headingPaddingLeft: PropTypes.string,
    headingPaddingRight: PropTypes.string,
    headingPaddingTop: PropTypes.string,
    headingShadow: PropTypes.string,
    headingSize: PropTypes.string,
    headingTracking: PropTypes.string,
    headingTransform: PropTypes.string,
    headingTransition: PropTypes.string,
    headingType: PropTypes.string,
    headingWeight: PropTypes.string,
    headingWidth: PropTypes.string,
    headingZIndex: PropTypes.number,
};

export default captionPropTypes;
